UrlStorage blacklist of forwarded headers
umccr/htsget-rs pull request #246
Opened 2024-05-16 15:50 UTC by KrKOo

This PR introduces the ability to define headers that should not be forwarded when `forward_headers` is enabled, as described in issue #243.

## Example config
```
...
[resolvers.storage]
url = "http://localhost:8080"
response_url = "https://example.com"
forward_headers = true
header_blacklist = ["Host"]
...
```

2024-05-16 23:45 UTC, brainstorm commented
This is great, thanks @KrKOo! I'm missing some documentation though, could you please describe your example in the docs and provide the resolver config you mentioned in the description of this PR?

Thanks again!

@mmalenic Any other observations? Does this PR fit with your recent hyper->reqwest transition?

2024-05-17 00:37 UTC, mmalenic requested changes
Thanks a lot for this @KrKOo. This is really good, and thanks for testing. Other than some documentation like @brainstorm  said, could you please also run `cargo fmt`, this should fix the CI tests. 

> @mmalenic Any other observations? Does this PR fit with your recent hyper->reqwest transition?

All good in relation to hyper/reqwest, these changes aren't affecting that portion of the code as they only edit the out-going headers in the URL tickets.

2024-05-17 12:58 UTC, KrKOo commented
Hey, while writing the docs I realized, that the headers were not removed from the request made by htsget-rs to the resource server, so I added that as well.

2024-05-19 23:28 UTC, mmalenic commented
This is great, thanks @KrKOo!

2024-05-19 23:28 UTC, mmalenic approved these changes

2024-05-19 23:33 UTC, merged

2024-05-19 23:33 UTC, brainstorm commented
Thanks again @KrKOo for your contribution! 🎉