Refactor commonalities across all formats.
umccr/htsget-rs pull request #52
Opened 2021-07-14 06:14 UTC by mmalenic

This refactors some commonalities across the formats, by creating a trait. Currently there is further duplicate code, however this will be removed upon completing this pull request.

Closes #48.

2021-07-14 08:28 UTC, mmalenic commented
I've put the common code in search.rs, however we can change this if we want.

Currently there is still a bit of repeated code, however the solution is unclear to me.
I see a few options:
1) We could introduce a few wrapper traits to refactor the commonalities. However, this seems a bit contrived, and may hurt readability.
2) Inside of noodles, some common traits could be introduced. However, the design decisions may also be unclear here, because not all formats share the same commonalities, and it may be difficult to design traits for them because of differences under the hood.
3) We could live with the code duplication. There is an argument to be made for the separate file formats being separate because they work slightly differently.

Let me know your thoughts if you would like to @brainstorm, @CastilloDel, @zaeleus :slightly_smiling_face:

2021-07-14 09:37 UTC, CastilloDel commented
The changes seem good to me! I'm not sure which of the options we should take. Maybe we could do two traits, one for variants formats (VCF and BCF) and one for reads formats (BAM and CRAM), that would make sense and could allow deleting some code duplications.

2021-07-14 10:06 UTC, mmalenic commented
Thanks @CastilloDel, I think a few traits to refactor the commonalities is the way to go. Counter intuitively, the common code isn't across reads and variants. For example https://github.com/umccr/htsget-rs/blob/051a04b80affc58c03478864e99b0d5cb8adcadc/htsget-search/src/htsget/bam_search.rs#L43-L54, https://github.com/umccr/htsget-rs/blob/051a04b80affc58c03478864e99b0d5cb8adcadc/htsget-search/src/htsget/vcf_search.rs#L45-L56 and https://github.com/umccr/htsget-rs/blob/051a04b80affc58c03478864e99b0d5cb8adcadc/htsget-search/src/htsget/bcf_search.rs#L45-L56

It seems like the most commonalities are shared between the formats that use VirtualPosition.

2021-07-14 10:10 UTC, CastilloDel commented
That is interesting, but I guess it makes sense, since, from what I saw in the CRAM implementation, it was really different from the others ones.

2021-07-15 03:10 UTC, brainstorm commented
Good job and discussions IRL about this yesterday @mmalenic. At first I had the reads vs variants intuition that @CastilloDel pointed out, but after our chat and reviewing this PR I do think that the `BlockPosition` and `VirtualPosition` traits work quite well, tbh, good observation and study Marko.

That being said, I see some methods like `get_byte_ranges_for_all()` that do seem to still be repeated across formats? But I bet that refactoring at this level of granularity (functions) is still pending (draft PR after all).

All in all I'd say the current draft seems to be a good direction compared with point 3 alternative (code duplication), which works but let's say that we find a way to optimize seek() or extract VirtualPositions faster (contrived example)... I don't think that it'll be nice to go through each format implementation changing the same bits?

I'm unsure about point 1, I'd would need to see how those wrapper traits look like first. 

I'd leave @zaeleus to comment on point 2, but I guess he also found it hard to introduce traits across formats in Noodles... or perhaps he did a (huge) first pass implementing each spec individually and leaving the traits/refactor for later?

2021-07-16 01:54 UTC, zaeleus commented
> I'd leave @zaeleus to comment on point 2, but I guess he also found it hard to introduce traits across formats in Noodles... or perhaps he did a (huge) first pass implementing each spec individually and leaving the traits/refactor for later?

A little bit of both. While there may be formats that serialize, effectively, the same data, their underlying structures are quite different, e.g., SAM, BAM, and CRAM. In noodles, SAM is completely parsed, BAM is lazily parsed (and thus, fallible), and CRAM is (currently) raw field data. I'll have to investigate this more to figure out an approach to convergence.

In the case of this discussion, I'll add traits for the binning index formats (BAI, CSI, and tabix), taking CSI as the most abstract of the three. [As mentioned](https://github.com/umccr/htsget-rs/pull/52#issuecomment-879768346), CRAI has a different structure and doesn't store the same metadata.

2021-07-19 06:04 UTC, brainstorm approved these changes
Marko, serious good work you've put in there, kudos.

I left a few thoughts about the documentation, but I'm pleased to see this abstraction work for the purpose of reducing code duplication across formats... all things considered I think that we've generally won a significant simplification on each format, sacrificing a bit on the `search.rs` abstract/trait part, but I think it's satisfactory as it stands.

As an added bonus, I think that your work represents the idea that bioinformatics formats are not *that different* and the underlying particularities can be abstracted away at many levels... perhaps moving away from them altogether at some point in the future, favoring more optimized storage schemas instead of 10+ year old **file** formats with quite a bit of gotchas and baggage in each of them :)

2021-07-19 06:11 UTC, mmalenic commented
Thanks @brainstorm, for the feedback! :smile:

2021-07-19 09:13 UTC, CastilloDel requested changes
You did a really great job! 💯

2021-07-19 09:13 UTC, CastilloDel commented on htsget-search/src/htsget/cram_search.rs
>        // An implementation based on file size might be better.
This could be also solved now, right? The `head` method is already in the storage trait

2021-07-19 09:13 UTC, CastilloDel commented on htsget-search/src/htsget/search.rs
> +pub(crate) trait BgzfSearch<'a, S, I, R, H>: Search<'a, S, I, R, H>
I think they should even have proper names instead of letters. Just a letter is normally okay, but having four of them can be confusing.

2021-07-20 01:11 UTC, brainstorm commented
@mmalenic Happy to merge after Daniel's comments (which I second too).

2021-07-22 05:16 UTC, merged