Add benchmarks
umccr/htsget-rs pull request #59
Opened 2021-08-09 11:29 UTC by CastilloDel

Closes #46 

Before this is ready to get merge I need to add benchmarks for the htsget-search crate and I want to add running the benchmarks to the GitHub actions

2021-08-12 13:06 UTC, brainstorm requested changes
Fantastic work here, Daniel, well done!

Other than the couple of minor comments I left, I'd save one static benchmark that cleary shows the performance difference of the reference implementation against htsget-rs, as mentioned in Slack:

> Where does criterion-rs store the different results for the run(s)? Does it commit the .jsons back to the repository or save it in the GitHub Actions CI’s cache?
I’m thinking about having some sort of static plot in the README and then refer to the series of plots generated across releases, so that people can easily track the progress?

2021-08-12 13:12 UTC, CastilloDel commented on htsget-search/benches/benchmark.rs
> +    .sample_size(20)
Yes! Totally should've done that

2021-08-12 13:15 UTC, CastilloDel commented on htsget-http-actix/htsget-refserver-config.json
> +{
Seems reasonable

2021-08-12 13:17 UTC, brainstorm commented
As for the commiting .htmls and jsons back to the repo... maybe https://github.com/boa-dev/criterion-compare-action is a better solution actually?

2021-08-12 16:32 UTC, CastilloDel commented
It seems the action doesn't work :(
Something about an unsupported option
```
error: Unrecognized option: 'save-baseline'
error: bench failed
Error: The process 'cargo' failed with exit code 101
    at ExecState._setResult (/home/runner/work/_actions/jasonwilliams/criterion-compare-action/move_to_actions/dist/index.js:1:7880)
    at ExecState.CheckComplete (/home/runner/work/_actions/jasonwilliams/criterion-compare-action/move_to_actions/dist/index.js:1:7442)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/jasonwilliams/criterion-compare-action/move_to_actions/dist/index.js:1:6406)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
I'll put an issue

2021-08-12 18:32 UTC, CastilloDel commented
I think I found a work-around! Although it means the criterion action will have to run twice

2021-08-12 18:35 UTC, CastilloDel commented
Well, it failed again, but I think it is because it is trying to execute the benchmarks in the main branch, where it fails. Tomorrow I'll make a fork and try it 😥

2021-08-17 10:16 UTC, CastilloDel commented
> `.sh`? :)

Yes, it is just a little script to set up the GA4HG server. It consists of only two commands, but one of them is rather long. I was using it myself, so I thought it could be convenient to add it to the project. Of course, I can just put those two commands in the instructions to set up the server!

2021-08-18 01:09 UTC, brainstorm commented
Oh, sorry @CastilloDel, I just meant that the extension should be `.sh`:

![Screen Shot 2021-08-18 at 11 08 26 am](https://user-images.githubusercontent.com/175587/129820429-75ea5703-4c7a-46b2-9297-edb818d7eebf.png)

2021-08-21 17:48 UTC, CastilloDel commented
Ah! Yes!

2021-08-21 19:38 UTC, CastilloDel commented
Fixed!

2022-05-31 02:28 UTC, mmalenic commented
@brainstorm I think this might just be done now.

Thanks a lot @CastilloDel for all the code and guidance on how to structure the benchmarks.

Some recent changes:
* Refactor search and request benchmarks to use recent changes in htsget-rs.
* Some bug fixes in htsget-rs, such as byte ranges being inclusive for http headers.
* Add benchmark actions to main action.yml - runs only light benchmarks.

2022-05-31 03:07 UTC, brainstorm approved these changes
Amazing job, thanks @mmalenic! Nice forensics on the 1-off byte range bit, might have tricked you for a while :-!

Feel free to merge and move on to issues #85 and #75, we got this! :)

2022-05-31 03:09 UTC, merged